# -*- coding: utf-8 -*-
"""CódigoTomaDatos_V6_0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xSt0GeJTssyZ_QpBs7jMP_EJzX6jjk6C
"""

# ======================================================================================
# CÓDIGO DE MONITOREO INTEGRADO DE ENERGÍA CON SENSORES TUYA
# ======================================================================================
# -*- coding: utf-8 -*-

"""
Monitoreo integrado de energía con sensores Tuya.

OBJETIVO GENERAL
----------------
Este script consulta periódicamente la API de Tuya para leer datos de distintos medidores
instalados en varias viviendas. Después de obtener los datos, guarda dos versiones:

1. data_raw/<Vivienda>/<Sensor>.csv
   - Contiene la respuesta "cruda" de Tuya (sin conversiones de unidades).

2. data_conv/<Vivienda>/<Sensor>.csv
   - Contiene los datos transformados a unidades físicas interpretables
     (por ejemplo: voltaje en V, corriente en A, frecuencia en Hz, etc.).

Además, el script puede generar gráficas en vivo a partir de los archivos convertidos.

NUEVA FUNCIONALIDAD INCORPORADA
-------------------------------
Además del guardado individual por sensor, el script puede construir archivos unificados
por vivienda cuando existan dos fases independientes (por ejemplo V2FaseA y V2FaseB),
dejando ambas lecturas en una sola fila por timestamp.

También consolida automáticamente los archivos unificados y genera:
- una tabla global CSV
- un archivo GeoJSON global

CARACTERÍSTICAS PRINCIPALES
---------------------------
- Organización por vivienda y por sensor.
- Una única conexión OpenAPI a Tuya.
- Manejo robusto de errores transitorios.
- Manejo de expiración o invalidación de token/sesión.
- Reintentos automáticos ante fallos de red o autenticación.
- Soporte para tres tipos de medidores:
    * M1 : medidor trifásico con variables codificadas en base64.
    * V2 : medidores con una estructura/escala específica.
    * V3 : medidores con otra estructura/escala específica.
- Creación automática de archivos unificados por vivienda.
- Exportación automática a GeoJSON.
- Los sensores cuyo device_id aún no se conoce se omiten sin detener el programa.

NOTA IMPORTANTE
---------------
Este script está pensado para ejecutarse en Colab o Jupyter, por eso incluye la línea
de instalación con "!pip". Si lo vas a correr como script .py fuera de notebook, esa línea
debe reemplazarse por una instalación previa en terminal.

AUTOR / CONTEXTO
----------------
Código preparado para monitoreo residencial de variables eléctricas con dispositivos Tuya
y posterior análisis de consumo energético.
"""

# ======================================================================================
# 1) INSTALACIÓN E IMPORTACIÓN DE LIBRERÍAS
# ======================================================================================



import tuya_connector  # noqa: F401

import os
import csv
import time
import base64
import json
from datetime import datetime
from zoneinfo import ZoneInfo

from tuya_connector import TuyaOpenAPI

import pandas as pd
import matplotlib.pyplot as plt

# ======================================================================================
# 2) PARÁMETROS DE VISUALIZACIÓN EN VIVO
# ======================================================================================

GRAFICAR_CADA_N_RONDAS = 5
_ronda = 0


def graficar_estado_actual(data_folder_conv, viviendas):
    print("\n" * 3)
    print("📈 Gráficas (actualización en vivo) — leyendo CSV CONVERTIDOS...\n")

    archivos_unificados = {cfg["archivo_salida"] for cfg in UNIFICACIONES.values()}

    for viv in viviendas.keys():
        viv_folder = os.path.join(data_folder_conv, viv)

        if not os.path.isdir(viv_folder):
            continue

        archivos = [
            f for f in os.listdir(viv_folder)
            if f.endswith(".csv")
            and f not in archivos_unificados
            and not f.endswith("_tabla.csv")
        ]

        if not archivos:
            continue

        print(f"🏠 {viv}")

        for archivo in sorted(archivos):
            # aquí queda tu código actual de gráficas por sensor
            pass

        print()

    # Esta parte va una sola vez, no dentro del ciclo de sensores
    graficar_promedios_consumo_horario_disponible(
        data_folder_conv=data_folder_conv,
        unificaciones=UNIFICACIONES
    )


# ======================================================================================
# 3) CONFIGURACIÓN GENERAL DEL PROGRAMA
# ======================================================================================

API_ENDPOINT = "https://openapi.tuyaus.com"

# -----------------------------------------------------------------------------
# CREDENCIALES
# -----------------------------------------------------------------------------
os.environ["TUYA_ACCESS_ID"] = "devg78x5vga3syrxjdsg"
os.environ["TUYA_ACCESS_KEY"] = "723b31007c6c48c7bbac834688130ca7"

ACCESS_ID = os.getenv("TUYA_ACCESS_ID")
ACCESS_KEY = os.getenv("TUYA_ACCESS_KEY")

# -----------------------------------------------------------------------------
# PARÁMETROS DE REINTENTO Y TEMPORIZACIÓN
# -----------------------------------------------------------------------------
INTERVALO_MINUTOS = 1
MAX_REINTENTOS = 3
SLEEP_REINTENTO_S = 2

# -----------------------------------------------------------------------------
# PARÁMETROS DE RECONEXIÓN DE SESIÓN/TOKEN
# -----------------------------------------------------------------------------
MAX_RECONNECTS = 2
SLEEP_RECONNECT_S = 1.0
TZ_LOCAL = ZoneInfo("America/Monterrey")

# -----------------------------------------------------------------------------
# CARPETAS DE SALIDA
# -----------------------------------------------------------------------------

BASE_DIR = os.path.join(os.getcwd(), "Monitoreo_Tuya")
DATA_RAW_FOLDER = os.path.join(BASE_DIR, "data_raw")
DATA_CONV_FOLDER = os.path.join(BASE_DIR, "data_conv")

# ======================================================================================
# 4) CONFIGURACIÓN DE VIVIENDAS Y SENSORES
# ======================================================================================

VIVIENDAS = {
    "Vivienda1 - Doctor": {
        "V1Extra": {"tipo": "V1EXTRA_DUAL", "device_id": "eb47caff2a29e9fe2aos9i"},
    },
    "Vivienda2 - Ángel": {
        "V2FaseA": {"tipo": "V2", "device_id": "eb1410cb74c0a62739mty3"},
        "V2FaseB": {"tipo": "V2", "device_id": "eb109bcaa77dc6fe8baoxs"},
    },
    "Vivienda3 - María": {
        "V3FaseA": {"tipo": "V3", "device_id": "ebc36f971d1011543dfifw"},
        "V3FaseB": {"tipo": "V3", "device_id": "ebe1be117fd2724821law2"},
    },
    "DistritoTec": {
        "DistritoTec": {"tipo": "V3_DUAL", "device_id": "ebf910cd0a32bfc8eddulf"},
        "DistritoTecExtra": {"tipo": "V1EXTRA_DUAL", "device_id": "eb47caff2a29e9fe2aos9i"},
    },
    "JIH-V": {
        "JIH-V": {"tipo": "V3_DUAL", "device_id": "eb3977dc2118ab36adqrcn"},
    },
    "JIH-V5": {
        "JIH-V5": {"tipo": "V3_DUAL", "device_id": "eb9b2d93a765165bb6ofsa"},
    },
    "JIH-V7": {
        "JIH-V7": {"tipo": "V3_DUAL", "device_id": "eb16c87a7aeab1ddebaqt9"},
    },
    "JIH-V3A": {
        "JIH-V3A": {"tipo": "V3_DUAL", "device_id": "eb5f863004dd5c2e8bb6qj"},
    },
    "JIH-V3": {
        "JIH-V3": {"tipo": "V3_DUAL", "device_id": "ebbf50490c22e704efnkgg"},
    },
    "JIH-V8V9": {
        "JIH-V8": {"tipo": "V3_DUAL", "device_id": "eb4c2ad27d5482af38chb7"},
        "JIH-V9": {"tipo": "V3_DUAL", "device_id": "eb0463f2bbc9d0c6eeyult"},
    },
    "JIH-V1V2": {
        "JIH-V1": {"tipo": "V3_DUAL", "device_id": "ebfad55d9cdfab06fb47ru"},
        "JIH-V2": {"tipo": "V3_DUAL", "device_id": "eb7c9350db8d9d7a8bkzuh"},
    },
}

# ======================================================================================
# 4.1) CONFIGURACIÓN DE ARCHIVOS UNIFICADOS POR VIVIENDA
# ======================================================================================

UNIFICACIONES = {
    "Vivienda1 - Doctor": {
        "archivo_salida": "Medidor1.csv",
        "fase_A": "V1ExtraA",
        "fase_B": "V1ExtraB",
        "latitud": 25.6189821,
        "longitud": -100.2950499,
    },
    "Vivienda2 - Ángel": {
        "archivo_salida": "Medidor2.csv",
        "fase_A": "V2FaseA",
        "fase_B": "V2FaseB",
        "latitud": 25.646641,
        "longitud": -100.288357,
    },
    "Vivienda3 - María": {
        "archivo_salida": "Medidor3.csv",
        "fase_A": "V3FaseA",
        "fase_B": "V3FaseB",
        "latitud": 25.648629,
        "longitud": -100.279387,
    },
    "DistritoTec": {
        "archivo_salida": "DistritoTec.csv",
        "fase_A": "DistritoTecA",
        "fase_B": "DistritoTecB",
        "fase_C": "DistritoTecExtraA",
        "fase_D": "DistritoTecExtraB",
        "latitud": 25.651085,
        "longitud": -100.293008,
    },
    "JIH-V": {
        "archivo_salida": "JIH-V.csv",
        "fase_A": "JIH-VA",
        "fase_B": "JIH-VB",
        "latitud": 25.6517419,
        "longitud": -100.2801823,
    },
    "JIH-V5": {
        "archivo_salida": "JIH-V5.csv",
        "fase_A": "JIH-V5A",
        "fase_B": "JIH-V5B",
        "latitud": 25.6572990,
        "longitud": -100.2932674,
    },
    "JIH-V7": {
        "archivo_salida": "JIH-V7.csv",
        "fase_A": "JIH-V7A",
        "fase_B": "JIH-V7B",
        "latitud": 25.6503091,
        "longitud": -100.2782943,
    },
    "JIH-V3A": {
    "archivo_salida": "JIH-V3A.csv",
    "fase_A": "JIH-V3AA",
    "fase_B": "JIH-V3AB",
    "latitud": 25.6588765,
    "longitud": -100.2920832,
    },
    "JIH-V3": {
        "archivo_salida": "JIH-V3.csv",
        "fase_A": "JIH-V3A",
        "fase_B": "JIH-V3B",
        "latitud": 25.6642470,
        "longitud": -100.2934948,
    },
    "JIH-V8V9": {
        "archivo_salida": "JIH-V8V9.csv",
        "fase_A": "JIH-V8A",
        "fase_B": "JIH-V8B",
        "fase_C": "JIH-V9A",
        "fase_D": "JIH-V9B",
        "latitud": 25.6456972,
        "longitud": -100.2865871,
    },
    "JIH-V1V2": {
        "archivo_salida": "JIH-V1V2.csv",
        "fase_A": "JIH-V1A",
        "fase_B": "JIH-V1B",
        "fase_C": "JIH-V2A",
        "fase_D": "JIH-V2B",
        "latitud": 25.6572276,
        "longitud": -100.2918787,
    },
}

# ======================================================================================
# 5) CONEXIÓN INICIAL A TUYA
# ======================================================================================

print("Iniciando conexión con Tuya...")

openapi = TuyaOpenAPI(API_ENDPOINT, ACCESS_ID, ACCESS_KEY)
openapi.connect()

print("✅ Conexión con Tuya OK\n")

# ======================================================================================
# 6) FUNCIONES UTILITARIAS GENERALES
# ======================================================================================

def now_str():
    """
    Devuelve el timestamp actual en la zona horaria local definida.
    """
    return datetime.now(TZ_LOCAL).strftime("%Y-%m-%d %H:%M:%S")


def ensure_folder(path):
    """
    Crea una carpeta si no existe.
    """
    os.makedirs(path, exist_ok=True)


def _looks_like_token_issue(resp=None, exc: Exception = None) -> bool:
    """
    Heurística para detectar problemas de token o sesión.
    """
    if exc is not None:
        s = str(exc).lower()
        keywords = [
            "token", "expire", "expired", "invalid",
            "unauthorized", "auth", "forbidden", "signature"
        ]
        return any(k in s for k in keywords)

    if isinstance(resp, dict):
        success = resp.get("success", True)

        if success is False:
            code = str(resp.get("code", "")).lower()
            msg = str(resp.get("msg", "")).lower()
            message = str(resp.get("message", "")).lower()
            combined = " ".join([code, msg, message])

            keywords = [
                "token", "expire", "expired", "invalid",
                "unauthorized", "auth", "forbidden", "signature"
            ]
            return any(k in combined for k in keywords)

    return False


def _reconnect_openapi():
    """
    Reconstruye la conexión con la API de Tuya.
    """
    global openapi

    try:
        print("🔄 Re-conectando a Tuya (refresh token/sesión)...")
        openapi = TuyaOpenAPI(API_ENDPOINT, ACCESS_ID, ACCESS_KEY)
        openapi.connect()
        time.sleep(SLEEP_RECONNECT_S)
        print("✅ Re-conexión OK")
        return True, None

    except Exception as e:
        print(f"❌ Falló reconnect(): {e}")
        return False, e


def openapi_get_safe(path: str):
    """
    Ejecuta openapi.get(path) de forma segura, intentando resolver problemas
    de token/sesión mediante reconexión automática.
    """
    try:
        resp = openapi.get(path)

        if _looks_like_token_issue(resp=resp):
            for _ in range(MAX_RECONNECTS):
                ok, _e = _reconnect_openapi()
                if not ok:
                    break

                resp2 = openapi.get(path)
                if not _looks_like_token_issue(resp=resp2):
                    return resp2, None

            return resp, Exception(f"Posible problema de token/sesión: {resp}")

        return resp, None

    except Exception as e:
        if _looks_like_token_issue(exc=e):
            for _ in range(MAX_RECONNECTS):
                ok, _e = _reconnect_openapi()
                if not ok:
                    break

                try:
                    resp2 = openapi.get(path)
                    if not _looks_like_token_issue(resp=resp2):
                        return resp2, None
                except Exception as e2:
                    e = e2

            return None, e

        return None, e


def tuya_get_with_retry(path: str, max_retries=MAX_REINTENTOS):
    """
    Ejecuta una consulta GET a Tuya con reintentos normales adicionales.
    """
    last_err = None

    for _ in range(1, max_retries + 1):
        resp, err = openapi_get_safe(path)

        if err is None and resp is not None:
            return resp, None

        last_err = err
        time.sleep(SLEEP_REINTENTO_S)

    return None, last_err


def obtener_datos_V1EXTRA_DUAL(device_id, ts):
    """
    Obtiene datos de un dispositivo V1Extra que reporta dos canales.
    """
    path = f"/v2.0/cloud/thing/{device_id}/shadow/properties"
    resp, err = tuya_get_with_retry(path)

    if err or not resp:
        return None, None, err

    result = resp.get("result", {})
    props = result.get("properties", [])
    propiedades = {p["code"]: p.get("value") for p in props}

    datos_raw = {"timestamp": ts}
    for k, v in propiedades.items():
        datos_raw[k] = v

    voltage = propiedades.get("voltage_a", 0) / 10
    freq = propiedades.get("freq", 0) / 100

    datos_conv_split = {
        "V1ExtraA": {
            "timestamp": ts,
            "voltage_V": voltage,
            "current_A": propiedades.get("current_a", 0) / 1000,
            "power_W": propiedades.get("power_a", 0) / 10,
            "pf": propiedades.get("power_factor", 0) / 100,
            "freq_Hz": freq,
            "energy_Wh": propiedades.get("energy_forword_a", 0),
            "energy_reverse_Wh": propiedades.get("energy_reverse_a", 0),
            "direction": propiedades.get("direction_a", ""),
        },
        "V1ExtraB": {
            "timestamp": ts,
            "voltage_V": voltage,
            "current_A": propiedades.get("current_b", 0) / 1000,
            "power_W": propiedades.get("power_b", 0) / 10,
            "pf": propiedades.get("power_factor_b", 0) / 100,
            "freq_Hz": freq,
            "energy_Wh": propiedades.get("energy_forword_b", 0),
            "energy_reverse_Wh": propiedades.get("energy_reserse_b", 0),
            "direction": propiedades.get("direction_b", ""),
        },
    }

    return datos_raw, datos_conv_split, None


# ======================================================================================
# 7) FUNCIONES DEL MEDIDOR TIPO M1
# ======================================================================================

def decodificar_instantaneo(b64):
    """
    Decodifica una cadena base64 proveniente de los campos pa_instant o pb_instant.
    """
    try:
        if not b64:
            return (0.0, 0.0, 0.0)

        data = base64.b64decode(b64)

        if len(data) < 12:
            return (0.0, 0.0, 0.0)

        voltaje = int.from_bytes(data[0:2], "big") / 10.0
        corriente = int.from_bytes(data[2:5], "big") / 1000.0
        potencia = int.from_bytes(data[5:8], "big", signed=False) / 10.0

        return voltaje, corriente, potencia

    except Exception as e:
        print(f"⚠️ Error al decodificar {b64}: {e}")
        return (0.0, 0.0, 0.0)


# ======================================================================================
# 8) FUNCIONES DE OBTENCIÓN DE DATOS POR TIPO DE SENSOR
# ======================================================================================

def obtener_datos_V3_DUAL(device_id, ts, prefijo="Medidor"):
    path = f"/v2.0/cloud/thing/{device_id}/shadow/properties"
    resp, err = tuya_get_with_retry(path)

    if err or not resp:
        return None, None, err

    result = resp.get("result", {})
    props = result.get("properties", [])
    propiedades = {p["code"]: p.get("value") for p in props}

    datos_raw = {"timestamp": ts}
    for k, v in propiedades.items():
        datos_raw[k] = v

    datos_conv_split = {
        f"{prefijo}A": {
            "timestamp": ts,
            "voltage_V": propiedades.get("voltage_a", 0) / 10,
            "current_A": propiedades.get("current_a", 0) / 100,
            "power_W": propiedades.get("power_a", 0),
            "pf": propiedades.get("power_factor", 0) / 100,
            "freq_Hz": propiedades.get("freq", 0) / 100,
            "energy_Wh": propiedades.get("energy_forword_a", 0),
        },
        f"{prefijo}B": {
            "timestamp": ts,
            "voltage_V": propiedades.get("voltage_b", 0) / 10,
            "current_A": propiedades.get("current_b", 0) / 100,
            "power_W": propiedades.get("power_b", 0),
            "pf": propiedades.get("power_factor_b", 0) / 100,
            "freq_Hz": propiedades.get("freq", 0) / 100,
            "energy_Wh": propiedades.get("energy_forword_b", 0),
        },
    }

    return datos_raw, datos_conv_split, None

def obtener_datos_M1(device_id, ts):
    """
    Obtiene datos del medidor tipo M1.
    """
    path = f"/v2.0/cloud/thing/{device_id}/shadow/properties"
    resp, err = tuya_get_with_retry(path)

    if err or not resp:
        return None, None, err

    result = resp.get("result", {})
    props_list = result.get("properties", [])
    props = {p["code"]: p.get("value") for p in props_list}

    datos_raw = {"timestamp": ts}
    for k, v in props.items():
        datos_raw[k] = v

    total_forward = props.get("total_forward_energy", 0)
    total_reverse = props.get("reverse_energy_total", 0)

    pa_raw = props.get("pa_instant", "")
    pb_raw = props.get("pb_instant", "")

    volt_a, corr_a, pot_a = decodificar_instantaneo(pa_raw)
    volt_b, corr_b, pot_b = decodificar_instantaneo(pb_raw)

    datos_conv = {
        "timestamp": ts,
        "voltaje_A(V)": volt_a,
        "corriente_A(A)": corr_a,
        "potencia_A(W)": pot_a,
        "voltaje_B(V)": volt_b,
        "corriente_B(A)": corr_b,
        "potencia_B(W)": pot_b,
        "energia_directa(Wh)": total_forward,
        "energia_inversa(Wh)": total_reverse,
    }

    return datos_raw, datos_conv, None


def obtener_datos_V2(device_id, ts):
    """
    Obtiene datos de sensores con transformación tipo V2.
    """
    path = f"/v2.0/cloud/thing/{device_id}/shadow/properties"
    resp, err = tuya_get_with_retry(path)

    if err or not resp:
        return None, None, err

    result = resp.get("result", {})
    props = result.get("properties", [])
    propiedades = {p["code"]: p.get("value") for p in props}

    datos_raw = {"timestamp": ts}
    for k, v in propiedades.items():
        datos_raw[k] = v

    datos_conv = {
        "timestamp": ts,
        "voltage_V": propiedades.get("voltage_a", 0) / 10,
        "current_A": propiedades.get("current_b", 0) / 1000,
        "power_W": propiedades.get("power_b", 0) / 10,
        "pf": propiedades.get("power_factor_b", 0) / 100,
        "freq_Hz": propiedades.get("freq", 0) / 100,
        "energy_Wh": propiedades.get("energy_forword_b", 0),
    }

    return datos_raw, datos_conv, None


def obtener_datos_V3(device_id, ts):
    """
    Obtiene datos de sensores con transformación tipo V3.
    """
    path = f"/v2.0/cloud/thing/{device_id}/shadow/properties"
    resp, err = tuya_get_with_retry(path)

    if err or not resp:
        return None, None, err

    result = resp.get("result", {})
    props = result.get("properties", [])
    propiedades = {p["code"]: p.get("value") for p in props}

    datos_raw = {"timestamp": ts}
    for k, v in propiedades.items():
        datos_raw[k] = v

    datos_conv = {
        "timestamp": ts,
        "voltage_V": propiedades.get("voltage_a", 0) / 10,
        "current_A": propiedades.get("current_a", 0) / 100,
        "power_W": propiedades.get("power_a", 0),
        "pf": propiedades.get("power_factor", 0) / 100,
        "freq_Hz": propiedades.get("freq", 0) / 100,
        "energy_Wh": propiedades.get("energy_forword_a", 0),
    }

    return datos_raw, datos_conv, None


def obtener_datos_V1EXTRA(device_id, ts):
    """
    Obtiene datos de sensores tipo V1Extra.
    """
    path = f"/v2.0/cloud/thing/{device_id}/shadow/properties"
    resp, err = tuya_get_with_retry(path)

    if err or not resp:
        return None, None, err

    result = resp.get("result", {})
    props = result.get("properties", [])
    propiedades = {p["code"]: p.get("value") for p in props}

    datos_raw = {"timestamp": ts}
    for k, v in propiedades.items():
        datos_raw[k] = v

    datos_conv = {
        "timestamp": ts,
        "voltage_V": propiedades.get("voltage_a", 0) / 10,
        "current_A": propiedades.get("current_b", 0) / 1000,
        "power_W": propiedades.get("power_b", 0) / 10,
        "pf": propiedades.get("power_factor_b", 0) / 100,
        "freq_Hz": propiedades.get("freq", 0) / 100,
        "energy_Wh": propiedades.get("energy_forword_b", 0),
    }

    return datos_raw, datos_conv, None


# ======================================================================================
# 9) FUNCIÓN DE GUARDADO EN CSV
# ======================================================================================

def guardar_csv(base_folder, vivienda, sensor_name, datos: dict):
    """
    Guarda un diccionario de datos en un CSV individual por sensor.
    """
    carpeta = os.path.join(base_folder, vivienda)
    ensure_folder(carpeta)

    archivo = os.path.join(carpeta, f"{sensor_name}.csv")
    nuevo = not os.path.exists(archivo)
    cols = list(datos.keys())

    with open(archivo, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=cols)

        if nuevo:
            writer.writeheader()

        writer.writerow(datos)


# ======================================================================================
# 9.1) FUNCIONES PARA ARCHIVOS UNIFICADOS POR VIVIENDA
# ======================================================================================

def formatear_valor_csv_es(valor):
    """
    Formatea valores para exportarlos con estilo similar al Medidor2.csv:
    - separador de columnas ';'
    - decimales con coma
    """
    if valor is None:
        return ""

    if isinstance(valor, str):
        return valor

    if isinstance(valor, bool):
        return str(valor)

    if isinstance(valor, int):
        return str(valor)

    if isinstance(valor, float):
        if pd.isna(valor):
            return ""
        texto = f"{valor:.6f}".rstrip("0").rstrip(".")
        return texto.replace(".", ",")

    return str(valor)


def construir_fila_unificada(
    ts, latitud, longitud,
    datos_fase_a, datos_fase_b,
    datos_fase_c=None, datos_fase_d=None
):
    dt = datetime.strptime(ts, "%Y-%m-%d %H:%M:%S")

    fila = {
        "latitud": latitud,
        "longitud": longitud,
        "timestamp": f"{dt.day}/{dt.month}/{dt.year} {dt.hour}:{dt.minute:02d}",
        "day": dt.day,
        "month": dt.month,
        "year": dt.year,
        "hour": dt.hour,
        "minute": dt.minute,
    }

    def agregar_fase(sufijo, datos):
        if datos is None:
            return

        fila.update({
            f"voltage_V_{sufijo}": datos.get("voltage_V"),
            f"current_A_{sufijo}": datos.get("current_A"),
            f"power_W_{sufijo}": datos.get("power_W"),
            f"pf_{sufijo}": datos.get("pf"),
            f"freq_Hz_{sufijo}": datos.get("freq_Hz"),
            f"energy_Wh_{sufijo}": datos.get("energy_Wh"),
        })

        if "energy_reverse_Wh" in datos:
            fila[f"energy_reverse_Wh_{sufijo}"] = datos.get("energy_reverse_Wh")

        if "direction" in datos:
            fila[f"direction_{sufijo}"] = datos.get("direction")

    agregar_fase("A", datos_fase_a)
    agregar_fase("B", datos_fase_b)
    agregar_fase("C", datos_fase_c)
    agregar_fase("D", datos_fase_d)

    return fila


def guardar_csv_unificado(base_folder, vivienda, archivo_salida, fila: dict):
    """
    Guarda una fila en un CSV unificado por vivienda.
    Si el archivo ya existe pero no tiene las columnas correctas,
    lo reconstruye automáticamente.
    """
    carpeta = os.path.join(base_folder, vivienda)
    ensure_folder(carpeta)

    archivo = os.path.join(carpeta, archivo_salida)
    cols = list(fila.keys())

    fila_formateada = {k: formatear_valor_csv_es(v) for k, v in fila.items()}

    # ---------------------------------------------------------
    # VALIDAR SI EL ARCHIVO EXISTE Y TIENE LAS COLUMNAS CORRECTAS
    # ---------------------------------------------------------
    if os.path.exists(archivo):
        try:
            df_existente = pd.read_csv(archivo, sep=";")

            cols_existentes = set(df_existente.columns)
            cols_nuevas = set(cols)

            # Si faltan columnas clave → RECONSTRUIR ARCHIVO
            if not cols_nuevas.issubset(cols_existentes):
                print(f"♻️ Reescribiendo {archivo_salida} (estructura antigua detectada)")

                with open(archivo, "w", newline="", encoding="utf-8-sig") as f:
                    writer = csv.DictWriter(f, fieldnames=cols, delimiter=";")
                    writer.writeheader()
                    writer.writerow(fila_formateada)

                return

        except Exception:
            print(f"⚠️ Error leyendo {archivo_salida}, se reconstruye.")

            with open(archivo, "w", newline="", encoding="utf-8-sig") as f:
                writer = csv.DictWriter(f, fieldnames=cols, delimiter=";")
                writer.writeheader()
                writer.writerow(fila_formateada)

            return

    # ---------------------------------------------------------
    # CASO NORMAL: APPEND
    # ---------------------------------------------------------
    nuevo = not os.path.exists(archivo)

    with open(archivo, "a", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=cols, delimiter=";")

        if nuevo:
            writer.writeheader()

        writer.writerow(fila_formateada)


# ======================================================================================
# 10) RUTEADOR DE FUNCIONES SEGÚN TIPO DE SENSOR
# ======================================================================================

GETTERS = {
    "M1": obtener_datos_M1,
    "V2": obtener_datos_V2,
    "V3": obtener_datos_V3,
    "V1EXTRA_DUAL": obtener_datos_V1EXTRA_DUAL,
    "V3_DUAL": obtener_datos_V3_DUAL,
}

# ======================================================================================
# 10.1) FUNCIONES PARA CONSOLIDAR ARCHIVOS UNIFICADOS Y EXPORTAR A GEOJSON
# ======================================================================================

def leer_csv_unificado(path_csv):
    """
    Lee un CSV unificado exportado con separador ';' y convierte columnas numéricas.
    """
    if not os.path.exists(path_csv):
        return None

    try:
        df = pd.read_csv(path_csv, sep=";", on_bad_lines="skip")

        if df.empty:
            return None

        # Limpiar coordenadas
        for col in ["latitud", "longitud"]:
            if col in df.columns:
                df[col] = (
                    df[col]
                    .astype(str)
                    .str.replace(",", ".", regex=False)
                    .replace("nan", None)
                )
                df[col] = pd.to_numeric(df[col], errors="coerce")

        # Limpiar columnas numéricas potenciales
        cols_posibles = [
            "day", "month", "year", "hour", "minute",
            "voltage_V_A", "current_A_A", "power_W_A", "pf_A", "freq_Hz_A", "energy_Wh_A",
            "voltage_V_B", "current_A_B", "power_W_B", "pf_B", "freq_Hz_B", "energy_Wh_B",
            "energy_reverse_Wh_A", "energy_reverse_Wh_B", "voltage_V_C", "current_A_C",
            "power_W_C", "pf_C", "freq_Hz_C", "energy_Wh_C","energy_reverse_Wh_C",
            "voltage_V_D", "current_A_D", "power_W_D", "pf_D", "freq_Hz_D", "energy_Wh_D","energy_reverse_Wh_D"
        ]

        for col in cols_posibles:
            if col in df.columns:
                df[col] = (
                    df[col]
                    .astype(str)
                    .str.replace(",", ".", regex=False)
                    .replace("nan", None)
                )
                df[col] = pd.to_numeric(df[col], errors="coerce")

        # Timestamp
        if "timestamp" in df.columns:
            df["timestamp"] = pd.to_datetime(df["timestamp"], dayfirst=True, errors="coerce")

        return df

    except Exception as e:
        print(f"⚠️ Error leyendo CSV unificado {path_csv}: {e}")
        return None

def consumos_horarios_ultimo_dia_para_geojson(group):
    """
    Calcula consumos horarios del último día disponible y los devuelve
    como propiedades tipo consume6_7, consume7_8, etc.
    Valores en kWh.
    """

    props_consumo = {}

    if "timestamp" not in group.columns:
        return props_consumo

    group = group.sort_values("timestamp").copy()

    cols_energy = [
        col for col in ["energy_Wh_A", "energy_Wh_B", "energy_Wh_C", "energy_Wh_D"]
        if col in group.columns
    ]

    if len(cols_energy) == 0:
        return props_consumo

    group["energy_total_Wh"] = group[cols_energy].sum(axis=1, skipna=True)

    group = group.dropna(subset=["timestamp", "energy_total_Wh"])

    if len(group) < 2:
        return props_consumo

    t_max = group["timestamp"].max()
    t_min = t_max - pd.Timedelta(hours=24)

    df_24h = group[group["timestamp"] >= t_min].copy()

    df_h = (
        df_24h
        .set_index("timestamp")
        .resample("1h")["energy_total_Wh"]
        .last()
        .dropna()
        .reset_index()
    )

    if len(df_h) < 2:
        return props_consumo

    df_h["consumo_Wh"] = df_h["energy_total_Wh"].diff()
    df_h["consumo_kWh"] = df_h["consumo_Wh"] / 1000

    df_h.loc[df_h["consumo_Wh"] < 0, ["consumo_Wh", "consumo_kWh"]] = None
    df_h = df_h.dropna(subset=["consumo_kWh"]).copy()

    for _, row in df_h.iterrows():
        h_ini = int(row["timestamp"].hour)
        h_fin = (h_ini + 1) % 24

        nombre_prop = f"consume{h_ini}_{h_fin}"
        props_consumo[nombre_prop] = round(float(row["consumo_kWh"]), 4)

    props_consumo["consumo_ultimo_dia_kWh"] = round(
        float(df_h["consumo_kWh"].sum()),
        4
    )

    props_consumo["timestamp_inicio_consumos"] = str(df_h["timestamp"].min())
    props_consumo["timestamp_fin_consumos"] = str(df_h["timestamp"].max())

    return props_consumo

def construir_feature_geojson(group, lat, lon, id_punto):
    """
    Construye una feature GeoJSON para un punto agrupado por coordenadas.
    Toma los últimos valores medidos y calcula deltas entre las dos últimas
    observaciones válidas para fases A, B, C y D cuando existan.
    """
    if "timestamp" in group.columns:
        group = group.sort_values("timestamp").copy()
    else:
        group = group.copy()

    def ultimo_valor(col):
        if col in group.columns and group[col].notna().any():
            return a_python_scalar(group[col].dropna().iloc[-1])
        return None

    def delta_entre_ultimas(col):
        if col in group.columns:
            serie = group[col].dropna()
            if len(serie) >= 2:
                delta = a_python_scalar(serie.iloc[-1] - serie.iloc[-2])
                return delta if delta is not None and delta >= 0 else None
        return None

    def sumar_deltas(*args):
        valores = [x for x in args if x is not None]
        return sum(valores) if valores else None

    timestamp_penultimo = None
    if "timestamp" in group.columns:
        serie_ts = group["timestamp"].dropna()
        if len(serie_ts) >= 2:
            timestamp_penultimo = str(serie_ts.iloc[-2])

    props = {
        "id_punto": str(id_punto),
        "n_registros": int(len(group)),
        "timestamp_ultimo": str(ultimo_valor("timestamp")) if "timestamp" in group.columns else None,
        "timestamp_penultimo": timestamp_penultimo,
    }

    deltas_energy = []
    deltas_reverse = []

    for fase in ["A", "B", "C", "D"]:
        props.update({
            f"voltage_V_{fase}": ultimo_valor(f"voltage_V_{fase}"),
            f"current_A_{fase}": ultimo_valor(f"current_A_{fase}"),
            f"power_W_{fase}": ultimo_valor(f"power_W_{fase}"),
            f"pf_{fase}": ultimo_valor(f"pf_{fase}"),
            f"freq_Hz_{fase}": ultimo_valor(f"freq_Hz_{fase}"),
            f"energy_Wh_{fase}": ultimo_valor(f"energy_Wh_{fase}"),
            f"energy_reverse_Wh_{fase}": ultimo_valor(f"energy_reverse_Wh_{fase}"),
        })

        delta_energy = delta_entre_ultimas(f"energy_Wh_{fase}")
        delta_reverse = delta_entre_ultimas(f"energy_reverse_Wh_{fase}")

        props[f"energy_Wh_{fase}_delta_ultimas_2"] = delta_energy
        props[f"energy_reverse_Wh_{fase}_delta_ultimas_2"] = delta_reverse

        deltas_energy.append(delta_energy)
        deltas_reverse.append(delta_reverse)

        if f"direction_{fase}" in group.columns:
            props[f"direction_{fase}"] = ultimo_valor(f"direction_{fase}")

    props["energy_Wh_delta_total_ultimas_2"] = sumar_deltas(*deltas_energy)
    props["energy_reverse_Wh_delta_total_ultimas_2"] = sumar_deltas(*deltas_reverse)

    props_consumo_horario = consumos_horarios_ultimo_dia_para_geojson(group)
    props.update(props_consumo_horario)

    props = serializar_props(props)

    return {
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates": [float(lon), float(lat)]
        },
        "properties": props
    }

def a_python_scalar(valor):
    """
    Convierte escalares de pandas/numpy a tipos nativos de Python
    para que json.dump los pueda serializar.
    """
    if pd.isna(valor):
        return None

    # Tipos numpy/pandas con método item()
    if hasattr(valor, "item"):
        try:
            return valor.item()
        except Exception:
            pass

    # Timestamp u otros objetos de fecha
    if isinstance(valor, (pd.Timestamp, datetime)):
        return str(valor)

    return valor


def serializar_props(props: dict):
    """
    Convierte todos los valores de un diccionario a tipos serializables por JSON.
    """
    return {k: a_python_scalar(v) for k, v in props.items()}

def exportar_csv_unificado_a_geojson(path_csv, path_csv_salida, path_geojson_salida):
    """
    Convierte un único CSV unificado a:
    - una tabla CSV procesada
    - un archivo GeoJSON

    No concatena viviendas. Trabaja archivo por archivo.
    """
    df = leer_csv_unificado(path_csv)

    if df is None or df.empty:
        print(f"⚠️ No se pudo exportar {path_csv}: archivo vacío o no disponible.")
        return

    # Limpiar filas sin coordenadas
    df = df.dropna(subset=["latitud", "longitud"]).copy()

    if df.empty:
        print(f"⚠️ No se pudo exportar {path_csv}: no hay coordenadas válidas.")
        return

    # ID por punto
    df["id_punto"] = (
        df["latitud"].astype(str) + "_" + df["longitud"].astype(str)
    )

    features = []
    grouped = df.groupby(["id_punto", "latitud", "longitud"], dropna=True)

    for (id_p, lat, lon), group in grouped:
        feature = construir_feature_geojson(group, lat, lon, id_p)
        features.append(feature)

    geojson = {
        "type": "FeatureCollection",
        "features": features
    }

    # Guardar tabla procesada
    df.to_csv(path_csv_salida, index=False, encoding="utf-8-sig")

    # Guardar geojson
    with open(path_geojson_salida, "w", encoding="utf-8") as f:
        json.dump(geojson, f, ensure_ascii=False, indent=2)

    print(f"🗺️ Tabla procesada guardada en: {path_csv_salida}")
    print(f"🗺️ GeoJSON guardado en: {path_geojson_salida}")


def exportar_geojson_por_medidor(data_folder_conv, unificaciones):
    """
    Recorre cada archivo unificado configurado en UNIFICACIONES
    y genera su propio CSV procesado y su propio GeoJSON.
    """
    for viv, cfg in unificaciones.items():
        archivo_csv = os.path.join(data_folder_conv, viv, cfg["archivo_salida"])

        nombre_base = os.path.splitext(cfg["archivo_salida"])[0]
        archivo_csv_salida = os.path.join(data_folder_conv, viv, f"{nombre_base}_tabla.csv")
        archivo_geojson_salida = os.path.join(data_folder_conv, viv, f"{nombre_base}.geojson")

        exportar_csv_unificado_a_geojson(
            path_csv=archivo_csv,
            path_csv_salida=archivo_csv_salida,
            path_geojson_salida=archivo_geojson_salida
        )

def exportar_global_unificado(data_folder_conv, unificaciones):
    """
    Une todos los CSV unificados por vivienda en un solo CSV global
    y genera un único GeoJSON global.
    """
    dfs = []

    for viv, cfg in unificaciones.items():
        archivo_csv = os.path.join(data_folder_conv, viv, cfg["archivo_salida"])
        df = leer_csv_unificado(archivo_csv)

        if df is None or df.empty:
            print(f"⚠️ No se pudo incluir {archivo_csv} en el global.")
            continue

        df["vivienda"] = viv
        df["archivo_origen"] = cfg["archivo_salida"]
        dfs.append(df)

    if not dfs:
        print("⚠️ No hay datos para construir el CSV/GeoJSON global.")
        return

    # ---------------------------------------------------------
    # CSV GLOBAL: unir todas las filas de todos los medidores
    # ---------------------------------------------------------
    df_global = pd.concat(dfs, ignore_index=True)

    csv_global_out = os.path.join(data_folder_conv, "medidores_global.csv")
    df_global.to_csv(csv_global_out, index=False, encoding="utf-8-sig")
    print(f"📄 CSV global guardado en: {csv_global_out}")

    # ---------------------------------------------------------
    # GEOJSON GLOBAL: una feature por vivienda / punto
    # usando la lógica de última observación
    # ---------------------------------------------------------
    df_geo = df_global.dropna(subset=["latitud", "longitud"]).copy()

    if df_geo.empty:
        print("⚠️ No se pudo construir el GeoJSON global: no hay coordenadas válidas.")
        return

    df_geo["id_punto"] = (
        df_geo["latitud"].astype(str) + "_" + df_geo["longitud"].astype(str)
    )

    features = []
    grouped = df_geo.groupby(["id_punto", "latitud", "longitud"], dropna=True)

    for (id_p, lat, lon), group in grouped:
        feature = construir_feature_geojson(group, lat, lon, id_p)

        # Agregar vivienda más reciente al properties del feature
        if "vivienda" in group.columns and group["vivienda"].notna().any():
            vivienda_ult = group.sort_values("timestamp")["vivienda"].dropna().iloc[-1]
            feature["properties"]["vivienda"] = str(vivienda_ult)

        if "archivo_origen" in group.columns and group["archivo_origen"].notna().any():
            archivo_ult = group.sort_values("timestamp")["archivo_origen"].dropna().iloc[-1]
            feature["properties"]["archivo_origen"] = str(archivo_ult)

        features.append(feature)

    geojson_global = {
        "type": "FeatureCollection",
        "features": features
    }

    geojson_global_out = os.path.join(data_folder_conv, "medidores_global.geojson")
    with open(geojson_global_out, "w", encoding="utf-8") as f:
        json.dump(geojson_global, f, ensure_ascii=False, indent=2)

    print(f"🗺️ GeoJSON global guardado en: {geojson_global_out}")

def calcular_promedio_consumo_horario_disponible(path_csv):
    """
    Calcula el promedio de consumo horario disponible por hora del día.
    Usa toda la información existente en el archivo unificado.
    """

    df = leer_csv_unificado(path_csv)

    if df is None or df.empty:
        return None, None

    df = df.sort_values("timestamp").copy()

    # Energía total acumulada por ambas fases
    cols_energy = [
        col for col in ["energy_Wh_A", "energy_Wh_B", "energy_Wh_C", "energy_Wh_D"]
        if col in df.columns
    ]

    if len(cols_energy) == 0:
        return None, None

    df["energy_total_Wh"] = df[cols_energy].sum(axis=1, skipna=True)

    df = df.dropna(subset=["timestamp", "energy_total_Wh"])

    if len(df) < 2:
        return None, None

    # Último valor acumulado disponible por hora
    df_h = (
        df
        .set_index("timestamp")
        .resample("1h")["energy_total_Wh"]
        .last()
        .dropna()
        .reset_index()
    )

    if len(df_h) < 2:
        return None, None

    # Consumo horario real
    df_h["consumo_Wh"] = df_h["energy_total_Wh"].diff()
    df_h["consumo_kWh"] = df_h["consumo_Wh"] / 1000

    # Limpiar valores negativos o imposibles
    df_h.loc[df_h["consumo_Wh"] < 0, ["consumo_Wh", "consumo_kWh"]] = None

    df_h = df_h.dropna(subset=["consumo_kWh"]).copy()

    if df_h.empty:
        return None, None

    # Hora del día
    df_h["hora_dia"] = df_h["timestamp"].dt.hour

    # Promedio por hora del día
    df_prom = (
        df_h
        .groupby("hora_dia", as_index=False)
        .agg(
            consumo_promedio_kWh=("consumo_kWh", "mean"),
            consumo_promedio_Wh=("consumo_Wh", "mean"),
            n_observaciones=("consumo_kWh", "count")
        )
    )

    df_prom["hora"] = df_prom["hora_dia"].apply(lambda h: f"{h:02d}:00 - {h+1:02d}:00")

    return df_h, df_prom

def graficar_promedios_consumo_horario_disponible(data_folder_conv, unificaciones):
    """
    Grafica los promedios de consumo horario disponibles para cada vivienda.
    """

    print("\n⏱️ Promedio de consumo horario según datos disponibles\n")

    for viv, cfg in unificaciones.items():
        path_csv = os.path.join(data_folder_conv, viv, cfg["archivo_salida"])

        if not os.path.exists(path_csv):
            continue

        df_h, df_prom = calcular_promedio_consumo_horario_disponible(path_csv)

        if df_prom is None or df_prom.empty:
            print(f"⚠️ {viv}: aún no hay datos suficientes para calcular consumos horarios.")
            continue

        print(f"🏠 {viv} — {cfg['archivo_salida']}")

        tabla = df_prom[[
            "hora",
            "consumo_promedio_Wh",
            "consumo_promedio_kWh",
            "n_observaciones"
        ]].copy()

        tabla["consumo_promedio_Wh"] = tabla["consumo_promedio_Wh"].round(2)
        tabla["consumo_promedio_kWh"] = tabla["consumo_promedio_kWh"].round(4)

        print(tabla.to_string(index=False))

        plt.figure(figsize=(11, 4))
        plt.plot(
            df_prom["hora"],
            df_prom["consumo_promedio_kWh"],
            marker="o",
            linewidth=2
        )
        plt.title(f"Promedio de consumo horario disponible - {viv}")
        plt.xlabel("Hora del día")
        plt.ylabel("Consumo promedio [kWh]")
        plt.xticks(rotation=45, ha="right")
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.show()

# ======================================================================================
# 11) LOOP PRINCIPAL DE MONITOREO
# ======================================================================================

print(f"⚡ Iniciando monitoreo cada {INTERVALO_MINUTOS} minuto(s)...")
print("🕒 Los timestamps se están generando en hora local de America/Monterrey.")
print("💾 Guardado en dos salidas: data_raw (sin conversiones) y data_conv (con conversiones).")
print("🧩 Además, se generarán archivos unificados por vivienda cuando aplique.")
print("🗺️ También se generará automáticamente una tabla global y un GeoJSON global.")

try:
    ts = now_str()

    print(f"\n================== RONDA {ts} ==================")

    for viv, sensores in VIVIENDAS.items():
        print(f"\n🏠 {viv}")

        # Acá se almacenan temporalmente las fases leídas en esta ronda
        datos_unificacion_ronda = {}

        for sensor_name, info in sensores.items():
            tipo = info.get("tipo")
            device_id = info.get("device_id")

            if device_id is None or str(device_id).strip() == "":
                print(f"⏳ {sensor_name} ({tipo}): esperando device_id...")
                continue

            getter = GETTERS.get(tipo)
            if getter is None:
                print(f"⚠️ {sensor_name}: tipo desconocido '{tipo}'")
                continue

            if tipo == "V3_DUAL":
                datos_raw, datos_conv, err = getter(device_id, ts, prefijo=sensor_name)
            else:
                datos_raw, datos_conv, err = getter(device_id, ts)

            if err or datos_raw is None or datos_conv is None:
                print(f"❌ {sensor_name} ({tipo}): error -> {err}")
                continue

            if tipo == "V1EXTRA_DUAL" and sensor_name != "V1Extra":
                datos_conv = {
                    f"{sensor_name}A": datos_conv["V1ExtraA"],
                    f"{sensor_name}B": datos_conv["V1ExtraB"],
                }

            if tipo in ["V1EXTRA_DUAL", "V3_DUAL"]:
                guardar_csv(DATA_RAW_FOLDER, viv, sensor_name, datos_raw)

                cfg_uni = UNIFICACIONES.get(viv)

                for sub_sensor_name, sub_datos in datos_conv.items():
                    guardar_csv(DATA_CONV_FOLDER, viv, sub_sensor_name, sub_datos)

                    if cfg_uni is not None:
                        if sub_sensor_name == cfg_uni.get("fase_A"):
                            datos_unificacion_ronda["A"] = sub_datos
                        elif sub_sensor_name == cfg_uni.get("fase_B"):
                            datos_unificacion_ronda["B"] = sub_datos
                        elif sub_sensor_name == cfg_uni.get("fase_C"):
                            datos_unificacion_ronda["C"] = sub_datos
                        elif sub_sensor_name == cfg_uni.get("fase_D"):
                            datos_unificacion_ronda["D"] = sub_datos

                    direction_txt = sub_datos.get("direction", "NA")

                    print(
                        f"✅ {sub_sensor_name}: "
                        f"{float(sub_datos['voltage_V']):.1f}V | "
                        f"{float(sub_datos['current_A']):.3f}A | "
                        f"{float(sub_datos['power_W']):.1f}W | "
                        f"PF={float(sub_datos['pf']):.2f} | "
                        f"F={float(sub_datos['freq_Hz']):.2f}Hz | "
                        f"E={sub_datos['energy_Wh']} | "
                        f"Dir={direction_txt}"
                    )

            else:
                guardar_csv(DATA_RAW_FOLDER, viv, sensor_name, datos_raw)
                guardar_csv(DATA_CONV_FOLDER, viv, sensor_name, datos_conv)

                cfg_uni = UNIFICACIONES.get(viv)
                if cfg_uni is not None:
                    if sensor_name == cfg_uni["fase_A"]:
                        datos_unificacion_ronda["A"] = datos_conv
                    elif sensor_name == cfg_uni["fase_B"]:
                        datos_unificacion_ronda["B"] = datos_conv

                if tipo == "M1":
                    print(
                        f"✅ {sensor_name}: "
                        f"A {float(datos_conv['voltaje_A(V)']):.1f}V "
                        f"{float(datos_conv['corriente_A(A)']):.3f}A "
                        f"{float(datos_conv['potencia_A(W)']):.1f}W | "
                        f"B {float(datos_conv['voltaje_B(V)']):.1f}V "
                        f"{float(datos_conv['corriente_B(A)']):.3f}A "
                        f"{float(datos_conv['potencia_B(W)']):.1f}W"
                    )
                else:
                    print(
                        f"✅ {sensor_name}: "
                        f"{float(datos_conv['voltage_V']):.1f}V | "
                        f"{float(datos_conv['current_A']):.3f}A | "
                        f"{float(datos_conv['power_W']):.1f}W | "
                        f"PF={float(datos_conv['pf']):.2f} | "
                        f"F={float(datos_conv['freq_Hz']):.2f}Hz | "
                        f"E={datos_conv['energy_Wh']}"
                    )

        # ---------------------------------------------------------
        # CONSTRUCCIÓN DEL ARCHIVO UNIFICADO POR VIVIENDA
        # ---------------------------------------------------------
        cfg_uni = UNIFICACIONES.get(viv)
        if cfg_uni is not None:
            fase_a = datos_unificacion_ronda.get("A")
            fase_b = datos_unificacion_ronda.get("B")
            fase_c = datos_unificacion_ronda.get("C")
            fase_d = datos_unificacion_ronda.get("D")

            if fase_a is not None and fase_b is not None:
                fila_unificada = construir_fila_unificada(
                    ts=ts,
                    latitud=cfg_uni["latitud"],
                    longitud=cfg_uni["longitud"],
                    datos_fase_a=fase_a,
                    datos_fase_b=fase_b,
                    datos_fase_c=fase_c,
                    datos_fase_d=fase_d,
                )

                guardar_csv_unificado(
                    DATA_CONV_FOLDER,
                    viv,
                    cfg_uni["archivo_salida"],
                    fila_unificada
                )

                print(f"🧩 Archivo unificado actualizado: {cfg_uni['archivo_salida']}")
            else:
                print("⚠️ No se pudo construir archivo unificado en esta ronda: falta Fase A o Fase B.")

    # -----------------------------------------------------------------
    # GRÁFICAS (UNA SOLA VEZ)
    # -----------------------------------------------------------------
    graficar_estado_actual(DATA_CONV_FOLDER, VIVIENDAS)

    # -----------------------------------------------------------------
    # EXPORTACIONES
    # -----------------------------------------------------------------
    exportar_geojson_por_medidor(DATA_CONV_FOLDER, UNIFICACIONES)
    exportar_global_unificado(DATA_CONV_FOLDER, UNIFICACIONES)

    print("\n✅ Proceso ejecutado una sola vez.")

except KeyboardInterrupt:
    print("\n🛑 Proceso detenido por el usuario.")
